Algoritmo "exercicio2"

Var

       ano, idade: inteiro

Inicio

      //entrada
       escreva("Digite seu ano de nascimento: ")
       leia(ano)
       escreval()
      
      
      //processamento
      idade <- 2020 - ano
      

      //saída
      se idade >= 18 entao
         escreval("Bora moer, beber até cair hehe")
      senao
         escreval("Podemos falsificar um RG pra você meu amigo")
      fimse
      

Fimalgoritmo
