Algoritmo "exercicio12"

Var
      semanas, dias: inteiro
      meses: real

Inicio

      //entrada
      escreval("Quantas semanas de gestação: ")
      leia(semanas)

      
      //processamento
      dias <- semanas*7
      meses <- dias/30

      
      
      //saída
      escreval("A quantidade de dias de gestação é de: ",dias)
      escreval("A quantidade de meses de gestação é de: ",meses:1:1)

      

Fimalgoritmo