Algoritmo "exercicio5"

Var
// Seção de Declarações das variáveis 
// caractere(texto), inteiro, real (numeros com casas decimais),
// logico (verdadeiro/falso)
a,b,c: inteiro


Inicio
      Escreva("Qual o valor de A?")
      leia(a)
      
      Escreva("Qual valor de B?")
      leia(b)
      
      c <- a
      a <- b
      b <- c


      Escreva("O valor de A é ",a, " e o valor de B é ", b)

      
      

      


Fimalgoritmo