Algoritmo "exercicio7"

Var
// Seção de Declarações das variáveis 
// caractere(texto), inteiro, real (numeros com casas decimais),
// logico (verdadeiro/falso)
anoAtual, anoNasc, idade: inteiro

Inicio

      Escreva("Em que ano você nasceu: ")
      leia(anoNasc)
      escreva()

      anoAtual <- 2020
      idade <- anoAtual - anoNasc
      
      Escreval("Sua idade é:", idade)

      
      
      


Fimalgoritmo