Algoritmo "exercicio11"

Var
   dolar, cotDolar, valorReais: real


Inicio

      //entrada

      escreval("Digite o valor do produto em Dólar US$: ")
      leia(dolar)
      escreval("Digite o valor da cotação do Dolár hoje: ")
      leia(cotDolar)
      
      //processamento

      valorReais <- dolar * cotDolar
      
      
      //saída

      escreval("O valor do produto em Reais é de R$:",valorReais)

      

Fimalgoritmo